# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# azure-pipelines.yml
trigger:
- main

pool:
  name: 'Default'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true

- script: |
    python --version
    pip --version
  displayName: 'Verify Python Version'

- script: |
    python -m pip install --upgrade pip setuptools wheel
  displayName: 'Upgrade pip, setuptools, wheel'

- script: |
    pip install --upgrade selenium
    pip install -r requirements.txt --use-deprecated=legacy-resolver
    pip install allure-pytest
  displayName: 'Install Dependencies Safely'

- script: |
    pytest --maxfail=1 --disable-warnings --junitxml=reports/results.xml --alluredir=reports/allure || exit 0
  displayName: 'Run PyTest Tests'
  continueOnError: true

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/reports/results.xml'
    testResultsFormat: 'JUnit'
    failTaskOnFailedTests: true

- powershell: |
    if (!(Test-Path "reports")) { New-Item -ItemType Directory -Path reports }
  displayName: 'Ensure Reports Folder Exists'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'reports'
    ArtifactName: 'PyTest_Reports'
    publishLocation: 'Container'
  continueOnError: true