# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Default'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true

- script: |
    python --version
    pip --version
  displayName: 'Verify Python Version'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Dependencies'

- script: |
    pytest --maxfail=1 --disable-warnings --junitxml=results.xml
  displayName: 'Run PyTest Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/results.xml'
    testResultsFormat: 'JUnit'
    failTaskOnFailedTests: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)'
    ArtifactName: 'PyTest_Artifact'
    publishLocation: 'Container'

